---
title: A Covariance Matrix
author: Bernardo Reckziegel
date: '2018-09-08'
slug: a-covariance-matrix
categories:
  - R
  - finance
tags:
  - shrinkage
  - estimation
---

The function bellow is a transcription from the MATLAB code done by Ledoit&Wolf in their work: *Improved estimation of the covariance matrix of stock returns with an application to portfolio selection*, which can be found [here](http://www.ledoit.net/ole2.pdf). 

If you also want to take a look on the original programming source, check the Michael's Wolf [website](https://www.econ.uzh.ch/en/people/faculty/wolf/publications.html#9).

```{r}

covMarket <- function(x, shrink = TRUE) {
    
    # some operations work better with the matrix class
    if (is.matrix(x) != TRUE) {
        
        x <- as.matrix(x) 
        
    }
    
    # de-mean returns 
    t     <- nrow(x)
    n     <- ncol(x)
    meanx <- colMeans(x)
    x     <- sweep(x, 2, meanx, "-")
    xmkt  <- rowMeans(x)
    
    sample <- cov(cbind(x, xmkt)) * (t - 1) / t
    covmkt <- sample[1:n, n + 1]
    varmkt <- sample[n + 1, n + 1]
    sample <- sample[1:n, 1:n]
    prior  <- (covmkt %*% t(covmkt)) / varmkt
    diag(prior) <- diag(sample)
    
    if (shrink) {
        
        # compute shrinkage parameters
        c <- norm(sample - prior, type = 'F') ^ 2
        y <- as.matrix(x ^ 2)
        p <- (1 / t) * sum(colSums(t(y) %*% y)) - sum(colSums(sample ^ 2))
        
        # r is divided into diagonal and off-diagonal terms, 
        # and the off-diagonal term is itself divided into smaller terms 
        rdiag <- (1 / t) * sum(colSums(y ^ 2)) - sum(diag(sample) ^ 2)
        z     <- x * matrix(rep(xmkt, n), ncol = n)
        v1    <- (1 / t) * t((t(z) %*% y)) - matrix(rep(covmkt, n), ncol = n) * sample
        roff1 <- (sum(colSums(v1 * t(matrix(rep(covmkt, n), ncol = n)))) / varmkt) - (sum(diag(v1) * covmkt) / varmkt)
        v3    <- (1 / t) * t(z) %*% z - varmkt * sample
        roff3 <- sum(colSums(v3 * (covmkt %*% t(covmkt)))) / varmkt ^ 2 - sum(diag(v3) * covmkt ^ 2) / varmkt ^ 2
        roff  <- 2 * roff1 - roff3
        r     <- rdiag + roff
        
        # compute shrinkage constant
        k         <- (p - r) / c
        shrinkage <- max(0, min(1, k / t)) 
        
    } else {
        
        # use specified number
        shrinkage <- shrink
        
    }
    
    # compute the estimator
    sigma <- shrinkage * prior + (1 - shrinkage) * sample
    
    # organize and print the output
    out <- list(sigma = sigma, shrinkage = shrinkage)
    
    return(out)
    
}


```

The final output contains the shrinked matrix and the shrinkage intensity, respectively. 

This estimator is a weighted average of the sample covariance matrix and a "prior" (given by the Sharpe-Ratio as a single factor model).

As the authors argument, there is a strong consensus on the nature of the Sharpe-Ratio, in contrast to an arbitrary number of factors given by a pure statistical model ([PCA](https://en.wikipedia.org/wiki/Principal_component_analysis), for example).

The implicit assumptions used to derive this estimator are:

- Stock return are independent and identically distribuited (IID);
- The number os stocks is fixed (finite) as time realizations goes to infinity; and
- Stocks have a finite four moment, so the variance can be measured.

I hope this function can serve you well!


