---
title: The Dance of the Yield
author: Bernardo Reckziegel
date: '2018-11-14'
slug: the-dance-of-yield
categories:
  - finance
  - R
tags:
  - yieldcurve
  - ggplot2
---

Studying for the 2019 CFA Level III exam I came across a very interesting chapter on yield curve strategies. The content, among other things, explores the role of convexity and its importance in building custom views for expected returns. The code below intents to visually show that the US yields indeed change in a non-linear fashion very often. 

In theory, this can be used to concentrate or spread-out the portfolio maturity holdings. The retionale follows from convexity deffinition, which is a measure of the effect of non-linear shifts in interest-rates. 

In a porfolio management context, convexity is an "asset" because imposes an assimetry in bond returns that almost every player in the market is looking for: the bond increases more than sugested by duration metrics if interest-rates decrease. Convexity becomes even more valuable when interest-rates volatility are expected to increase as well.  

See the code.

```{r, message=FALSE, warning=FALSE, fig.align='center', fig.width=12}
# load libraries
library(Quandl)
library(tidyverse)
library(gganimate)
library(ggthemes)

# download the yield from Quandl
us_yields <- Quandl("USTREASURY/YIELD", collapse = "monthly", order = "asc")

# express the maturity holdings in months
maturities <- c("Date", 1/12, 2/12, 3/12, 6/12, 1, 2, 3, 5, 7, 10, 20, 30)
n <- nrow(us_yields)

# create the plot
p <- us_yields %>% 
    as_tibble() %>% 
    
    # change maturity names
    `colnames<-`(maturities) %>% 
    
    # tidy
    gather("maturity", "yields", -Date) %>%
    mutate_if(is_character, as.numeric) %>%
    
    # plot 
    ggplot(aes(x = maturity, y = yields, group = Date)) + 
    geom_smooth(level = 0.95, span = 0.75) +
    geom_point(size = 3, alpha = 0.75, color = 'steelblue') + 
    scale_x_continuous(limits = c(0, 30)) +  
    theme_fivethirtyeight() + 
    theme(legend.position = "none") +
    
    # animate
    labs(title    = "US Treasury Yield Curve Dynamics", 
         subtitle = "Constant Maturity Rates Actively Traded at Over-the-Counter: {frame_time}", 
         x        = "Maturity (Years)", 
         y        = "Yields", 
         caption  = "Source: US Treasury & Quandl.com") + 
    transition_time(Date) 

# animate
animate(plot = p, nframes = n,  fps = 5)

```


The main challenge to backtest [bullets](https://www.investopedia.com/terms/b/bulllet.asp) and [barbells](https://www.investopedia.com/terms/b/barbell.asp) strategies is how to set the *correct* prior conditional to the fact that time-series information vanishes often vary fast. Maybe factor analysis can play a role here (through level, stepness and curvature), but I don't expect the result to be soo significant. 

I shall come back to this topic in the future. 



